### ISSUE TITLE
errors in line 

### ISSUE THREAD

**Issue by Chzia** [DanMcInerney/fast-recon#1]
Traceback (most recent call last):
  File "fast-recon.py", line 75, in <module>
    main()
  File "fast-recon.py", line 69, in main
    br = start_browser()
  File "fast-recon.py", line 24, in start_browser
    br = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

root@kali:~/Documents/fast-recon#

**Comment by s55ma** [comment]
any fix for this issue?

**Comment by sv0** [comment]
fast-recon requires [geckodriver](https://github.com/mozilla/geckodriver/releases)

Go to https://github.com/mozilla/geckodriver/releases and download the latest version of geckodriver for your OS and CPU architecture.

Put it in PATH dir (says, $HOME/bin) or in case if you saved **geckodriver** to folder with fast-recon then   set PATH environment variable while running fast-recon:

    PATH=$PATH:. ./fast-recon.py -d example.com

**Comment by DanMcInerney** [comment]
Thx SV0.
