### ISSUE TITLE
Running Fast-recon error occurred

### ISSUE THREAD

**Issue by attacker34** [DanMcInerney/fast-recon#2]
Dear ,

I installed the tool in my linux OS and no exception while installing. But when i tried to run it against the target i got the exception like:

```

root@kali:~/pentest/fast-recon# python fast-recon.py -d "danmcinerney.org"
Traceback (most recent call last):
  File "fast-recon.py", line 75, in <module>
    main()
  File "fast-recon.py", line 69, in main
    br = start_browser()
  File "fast-recon.py", line 25, in start_browser
    br.implicitly_wait(10)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 767, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Missing 'type' parameter



```

Can you please guide me what should be done to remove this exception.

Thanks.

**Comment by docker0** [comment]
idiot you need to install google chrome and integrate with selenium>=2.44.0 using its drivers , noob scriptkiddi
